### ISSUE TITLE
Busy: Create New Table for Job Status Changes

### ISSUE THREAD

**Issue by 112523chen** [112523chen/Job-Application-Tracker-Web-App#16]
**Description:** create a new table to support one-to-many relationships that will be used later in later feature

**Task(s)**
- [ ] Mock up table schema
- [ ] Create a table in the database
- [ ] Update the `applications` table to have no reference to timestampz
- [ ] Migrate data from `applications` to a new table
- [ ] Update API to support database update
- [ ] Find and fix any bugs that may have been created
